#!/bin/sh
# Munin Plugin to display the number of feedburner
# RSS feed subscribers
# Ben Dowling - www.coderholic.com

# Change this to whatever sites you're interested in
websites="coderholic"

if [ "$1" = "autoconf" ]; then
        echo yes
        exit 0
fi

if [ "$1" = "config" ]; then

        echo 'graph_title Feedburner Subscriber Count'
        echo 'graph_args --base 1000 -l 0 '
        echo 'graph_vlabel subscribers'
        echo 'graph_category popularity'
        echo 'graph_info This graph shows feedburner subscriber count.'

        for site in $websites
        do
                echo "${site}.label ${site}"
                echo "${site}.draw LINE2"
                echo "${site}.info The number of subscribers"
        done
        exit 0
fi

for site in $websites
do
        value=$(curl -L -s "http://feedburner.google.com/awareness/1.0/GetFeedData?uri=${site}"| grep -E 'circulation="[0-9]+"' -o | grep -E "[0-9]+" -o)
        echo "${site}.value ${value}"
done
